In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import matplotlib.animation as ani
import matplotlib.cm as cm 

# allows animation features within notebook
%matplotlib notebook

In [4]:
timesteps = np.arange(-1,1,0.01)

In [47]:
class particle:
    def __init__(self, timesteps, mass = 1, charge = 1, force = np.zeros(timesteps.size), dt = timesteps.size/1000):
             
        self.mass = mass
        self.charge = charge
        self.timesteps = timesteps
        self.force = force
        self.dt = dt
        
        self.pos = np.zeros((self.timesteps.size, 3))
        self.vel = np.zeros((self.timesteps.size, 3))
        self.accel = np.zeros((self.timesteps.size, 3))
        self.force = np.zeros((self.timesteps.size, 3)) #net force on the particle
        
    def update(self):
        self.accel - self.forcce/self.mass
        self.vel = self.accel*dt
        self.pos = self.vel*dt
        
        

In [55]:
# now we set up an array of particle objects


def make_particle_list(N): # makes list of N particles
    Particle_list = []
    for i in range(N):
        Particle_list.append(particle(timesteps))
    return Particle_list

def set_positions(Particle_list): # sets INITIAL positions of particles as (1,0,0) , (2,0,0) ...
    for i in range(len(Particle_list)):
        Particle_list[i].pos = np.array([i,0,0])
    
def calc_forces(particle, Particle_list): # calcs forces between particles
    for i in range(len(Particle_list)):
        for j in range(len(Particle_list)):
            if i == j:
                Particle_list[i].force+=0
            else:
                sep = Particle_list[i].pos - Particle_list[j].pos
                Particle_list[i].force+= sep/(np.linalg.norm(sep))**3



In [56]:
particles = make_particle_list(2)
set_positions(particles)
calc_forces(particles[0],particles)

print(particles[0].pos)
print(particles[0].force)





[0 0 0]
[[-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [