In [5]:
import numpy as np
import matplotlib.pyplot as plt 
import matplotlib.animation as ani
import matplotlib.cm as cm 
from threading import Thread
from time import sleep
from main import MainCycle
# particle as particle




# allows animation features within notebook
%matplotlib notebook

In [7]:
cycle = MainCycle(3,0.1)
cycle.start_cycle(1)
print(cycle.particle_list[0].pos)

1.428355697996826    1.428355697996826
1.749371315644566    1.7493713156445663
2.02    2.02
2.258428657274788    2.258428657274788
2.4739846402110097    2.4739846402110097
2.6722088241752364    2.6722088241752364
2.856711395993652    2.856711395993652
3.03    3.03
3.1939004367700634    3.1939004367700634
3.349791038258954    3.3497910382589535
3.498742631289132    3.498742631289132
[[ 0.61697464  0.52360152  0.60438708]
 [ 0.60359374  0.48614582  0.64763944]
 [ 0.57766518  0.4247203   0.71134774]
 [ 0.53998377  0.34780281  0.77945541]
 [ 0.49144523  0.26015741  0.84314869]
 [ 0.43313945  0.16510582  0.89734624]
 [ 0.36635384  0.06540368  0.93893941]
 [ 0.29253982 -0.03646259  0.96601808]
 [ 0.21326801 -0.13818502  0.97750788]
 [ 0.1301813  -0.23761861  0.97298007]
 [ 0.04494961 -0.33279368  0.95253761]
 [-0.04077274 -0.42193759  0.91673674]]


In [ ]:
def calc_potential(particle_list):
    