In [9]:
import numpy as np
import matplotlib.pyplot as plt 
import matplotlib.animation as ani
import matplotlib.cm as cm 
from threading import Thread
from time import sleep
from main import MainCycle
# particle as particle




# allows animation features within notebook
%matplotlib notebook

In [10]:
cycle = MainCycle(3,0.1)
cycle.start_cycle(1)
print(cycle.particle_list[0].pos)

1.428355697996826    1.428355697996826
1.749371315644566    1.749371315644566
2.02    2.02
2.258428657274788    2.258428657274788
2.4739846402110097    2.47398464021101
2.6722088241752364    2.6722088241752364
2.856711395993652    2.856711395993652
3.03    3.0300000000000002
3.1939004367700634    3.1939004367700634
3.349791038258954    3.349791038258954
3.498742631289132    3.498742631289132
[[ 0.52970827  0.62109262  0.59477147]
 [ 0.54130256  0.57601653  0.62872609]
 [ 0.55950496  0.49756836  0.67784949]
 [ 0.57782607  0.39612116  0.72753355]
 [ 0.59153914  0.27871631  0.76973935]
 [ 0.59774857  0.15059431  0.80007375]
 [ 0.59482707  0.01614924  0.81610046]
 [ 0.58200949 -0.12068395  0.81657843]
 [ 0.55914904 -0.25630232  0.80110016]
 [ 0.52656655 -0.38741408  0.7698948 ]
 [ 0.48494867 -0.51105836  0.72370169]
 [ 0.4352723  -0.62463805  0.66367563]]


In [14]:
print(cycle.counter)
    

AttributeError: 'MainCycle' object has no attribute 'counter'

AttributeError: 'MainCycle' object has no attribute 'counter'